# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpaceX_API' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SpaceX_API
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxDataSources', '~> 4.0.1'

  target 'SpaceX_APITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpaceX_APIUITests' do
    # Pods for testing
  end

end
